spring.application.name=ecommerce

# MySQL Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

project.image=images/

spring.sql.init.mode=never

spring.app.jwtSecret=${JWT_SECRET:ZGV2LWp3dC1zZWNyZXQta2V5LWZvci1sb2NhbC11c2Utb25seS0xMjM0NTY3ODkw}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
spring.app.jwtCookieName=springBootEcom
server.port=8080


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.example.ecommerce=DEBUG
